name: ""
services:
  datadog-agent:
    # https://hub.docker.com/r/datadog/agent/tags
    image: gcr.io/datadoghq/agent:latest
    environment:
    - "DD_HOSTNAME=sqlserver"
    env_file:
    - '~/sandbox.docker.env'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    - '$PWD/conf.d/sqlserver.d:/etc/datadog-agent/conf.d/sqlserver.d'

  ssql:
    # https://mcr.microsoft.com/v2/mssql/server/tags/list
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
    - "ACCEPT_EULA=Y"
    - "MSSQL_SA_PASSWORD=Password1!"
  

